# Generated by Django 4.2.5 on 2024-02-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(default=0, max_length=100),
        ),
    ]
